#!/bin/bash
sudo apt-get update
sudo apt-get install -y \
  autoconf automake autotools-dev curl python3 python3-pip \
  libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex \
  texinfo gperf libtool patchutils bc zlib1g-dev libexpat1-dev \
  ninja-build git cmake libglib2.0-dev libslirp-dev

git clone --depth=1 https://github.com/riscv/riscv-gnu-toolchain
cd riscv-gnu-toolchain

sudo mkdir -p /opt/riscv && sudo chown "$USER":"$USER" /opt/riscv
./configure --prefix=/opt/riscv
make -j"$(nproc)" linux

echo 'export PATH=/opt/riscv/bin:$PATH' >> ~/.bashrc
pip3 install --user scons
