# Top-level SCons entry point for building bareOS.
# Handles environment discovery, toolchain selection, and shared helpers.

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

from SCons.Script import (  # type: ignore[import-not-found]
	ARGUMENTS,
	Alias,
	COMMAND_LINE_TARGETS,
	Environment,
	Exit,
	GetOption,
	Help,
)

# QEMU Setup -------------------------------------------------------------------------------------------

Help(
		"""BareOS build targets

Usage:
  scons [target] [debug]
  scons -c
  scons -h

Targets:
  build        Build the kernel ELF image and regenerate QEMU flags.
  run          Build the kernel and launch it under QEMU.
  debug        Optional companion target enabling the GDB stub.

Options:
  -c, --clean  Remove SCons state and all build outputs.
"""
)

Alias("debug", None)

# Return the first riscv64 GCC prefix detected on PATH.
def _detect_cross_compiler() -> str:
	user_override = ARGUMENTS.get("arch")
	if user_override:
		return user_override

	for candidate in (
		"riscv64-unknown-elf",
		"riscv64-unknown-linux-gnu",
		"riscv64-linux-gnu",
	):
		if shutil.which(f"{candidate}-gcc"):
			return candidate
	print("[Error] no RISC-V cross compiler found on PATH")
	Exit(1)

# Attempt to remove the provided path while logging failures.
def _safe_remove(path: Path) -> None:
	try:
		if path.is_dir():
			print(f"scons: Removing build directory: {path}")
			shutil.rmtree(path)
		elif path.is_file():
			print(f"scons: Removing build artifact: {path}")
			path.unlink()
	except OSError as exc:  # pragma: no cover - logging of failure only
		print(f"scons: Failed to remove {path}: {exc}")

# Remove SCons state and build outputs for a pristine tree.
def _perform_clean(build_root: Path) -> None:
	_safe_remove(build_root)
	_safe_remove(Path(".sconsign.dblite"))
	_safe_remove(Path("bareOS.elf"))

# Emit version.h using the latest reachable git tag. Displayed to the user at startup. 
def _write_version_header(header_path: Path) -> None:
	try:
		rev = subprocess.check_output(
			["git", "rev-list", "--tags", "--max-count=1"],
			text=True,
			stderr=subprocess.DEVNULL,
		).strip()
		tag = subprocess.check_output(
			["git", "describe", "--tags", rev],
			text=True,
			stderr=subprocess.DEVNULL,
		).strip()
	except subprocess.CalledProcessError:
		tag = "alpha0-0.0.0"

	match = re.match(r"alpha(\d+)-(\d+)\.(\d+)\.(\d+)", tag)
	alpha, major, minor, patch = match.groups() if match else ("0", "0", "0", "0")

	contents = f"""#ifndef VERSION_H
	#define VERSION_H
	/* Automatically generated by SCons. */
	#define VERSION_ALPHA {alpha}
	#define VERSION_MAJOR {major}
	#define VERSION_MINOR {minor}
	#define VERSION_PATCH {patch}

	#endif

	"""
	header_path.write_text(contents)


ARCH = _detect_cross_compiler()
BUILD_DIR = Path(".build")
INCLUDE_DIR = Path("kernel/include")
LIB_DIR = Path("library")
LIB_INCLUDE_DIR = LIB_DIR / "include"
LD_FILE = Path("kernel/kernel.ld")
MAP_FILE = File(str(BUILD_DIR / "kernel.map"))

if GetOption("clean"):
	_perform_clean(BUILD_DIR)

PORT = 6999
CFLAGS = " ".join(
	[
		"-std=gnu2x",
		"-Wall",
		"-Werror",
		"-fno-builtin",
		"-nostdlib",
		"-nostdinc",
		"-march=rv64imac_zicsr",
		"-mabi=lp64",
		"-mcmodel=medany",
		"-O0",
		"-g",
	]
)
LFLAGS = f"-nostdlib -Map {MAP_FILE} -T {LD_FILE}"
AFLAGS = "-march=rv64imac_zicsr -mabi=lp64 -g"
QFLAGS = (
	"-M virt -bios none -cpu rv64,sstc=false -m 128M "
	"-chardev stdio,id=uart0 -serial chardev:uart0 -display none"
)

_write_version_header(Path("kernel/include/system/version.h"))

env = Environment(
	CC=f"{ARCH}-gcc",
	AS=f"{ARCH}-as",
	LINK=f"{ARCH}-ld",
	QEMU="qemu-system-riscv64",
	GDB=f"{ARCH}-gdb",
	CPPPATH=[str(INCLUDE_DIR), str(LIB_INCLUDE_DIR)],
	LINKFLAGS=LFLAGS,
	memmap=MAP_FILE,
	qflags=QFLAGS,
	port=PORT,
	DEBUG_MODE=(
		"debug" in COMMAND_LINE_TARGETS
		or os.getenv("BAREOS_QEMU_DEBUG") == "1"
	),
)
env.Append(ENV={"PATH": os.environ["PATH"]}, CFLAGS=CFLAGS, ASFLAGS=AFLAGS)

script = env.SConscript(
	"SConscript.py",
	variant_dir=str(BUILD_DIR),
	duplicate=False,
	exports="env",
)
